### ISSUE TITLE
Add support for AAAA records

### ISSUE THREAD

**Issue by cyberpower678** [willswire/unifi-ddns#50]
Some ISPs only assign an IPv6 and no IPv4 IP to their customers.  As a result this utility will fail to update anything at all when trying to assign a domain to it.  This utility is useful beyond the realms of the Unifi gateways.  I'm able to plug in the same update URLs into FritzBox's and those with IPv4 pass the updated record to CloudFlare successfully.

I have to routers that currently do not have IPv4, and their records are not being updated subsequently.

Would it be possible to implement AAAA support?

**Comment by willswire** [comment]
We could Ppotentially adding some conditional logic in the script to check for the submitted IP (looking for `:` character for example) to determine the type of record to create. If anyone wants to contribute a PR, I'd be happy to review and merge!

**Comment by isAdrisal** [comment]
Is this still needing implementation? The code seems to already look for `AAAA` records if the IP address doesn't contain a `.`.

https://github.com/willswire/unifi-ddns/blob/main/src/index.js#L35
```js
async findRecord(zone, name, isIPV4 = true) {
  const rrType = isIPV4 ? "A" : "AAAA";
```

**Comment by cyberpower678** [comment]
I'm not seeing any AAAA records on my IPv6 only domains.

**Comment by isAdrisal** [comment]
Are the two IPv6 domains using subdomains? There's a note in the readme that for IPv4 subdomains, the `A` record needs to be created manually first. Perhaps it's similar for `AAAA`?

**Comment by cyberpower678** [comment]
You might be right.  I've created AAAA records for the two and pointed it to ::.  Let's see if they actually populate.

**Comment by cyberpower678** [comment]
Nope.  It's not updating my records.

**Comment by cyberpower678** [comment]
https://github.com/willswire/unifi-ddns/pull/67

This should fully implement the feature which should allow both IPv4 and IPv6 to be updated simultaneously.
