### ISSUE TITLE
Deploy to Cloudflare worker failed

### ISSUE THREAD

**Issue by Mn3m0syn3** [willswire/unifi-ddns#73]
Deploy to cloudflare failed and did not create the worker. The only error displayed is below:
![image](https://github.com/willswire/unifi-ddns/assets/22564104/35952cc7-54ca-4432-b9fa-b4ea08fd0ddc)

**Comment by tjohnson-2** [comment]
Got the same issue. Went to my forked repository on GitHub and manually ran the deploy script. Refreshed the deployment page on CF workers and it loaded successfully. Ensure the API key is created exactly as per the deployment notes.
