### ISSUE TITLE
Temporary error in DDNS server response: DDNS server busy

### ISSUE THREAD

**Issue by didacdomenech** [willswire/unifi-ddns#84]
I was experiencing this error when testing the changes in my UDM-Pro:
```
~# inadyn -n -1 --force -f /run/ddns-ppp0-inadyn.conf
inadyn[2075283]: In-a-dyn version 2.12.0 -- Dynamic DNS update client.
inadyn[2075283]: Failed resolving hostname [REDACTED]: Name or service not known
inadyn[2075283]: Update forced for alias [REDACTED], new IP# [REDACTED]
inadyn[2075283]: Temporary error in DDNS server response: DDNS server busy, try later
inadyn[2075283]: Will retry again in 600 sec ...
```

My configuration is as follows
**Service:** custom
**Hostname:** redactedhostname.redacted.com
**Username:** redacted.com
**Password:** [REDACTED_API_TOKEN]
**Server:** unifi-cloudflare-ddns.REDACTED.workers.dev/update?ip=%i&hostname=%h

I finally fixed this by **manually adding the entry on cloudflare**, then whenever the IP changes, the script executes successfully. I don't know what rationale is behind not being able to add new entries maybe someone more experienced could explain this.

**Comment by bsdkurt** [comment]
This is covered in the documentation already.
https://github.com/willswire/unifi-ddns?tab=readme-ov-file#important-notes
