### ISSUE TITLE
Compatible with UCG Ultra running 4.1.9

### ISSUE THREAD

**Issue by nathanu** [willswire/unifi-ddns#91]
Hello, just followed along with you directions on my Cloud Gateway Ultra but I never see ddclient start and cannot find it in /run after enabling and configuring in the WebUI. Any chance i'm doing something wrong or does the UCG and USG support dynamic dns differently?

**Comment by willswire** [comment]
Hey @nathanu! Thanks for checking out the project. Have you tried tailing the logs on the worker to see if your device is reaching out to Cloudflare? Using the [wrangler CLI](https://developers.cloudflare.com/workers/wrangler/install-and-update/), you can run something like `wrangler tail unifi-cloudflare-ddns --format=json --ip=<your_device_public_ip>` to filter specifically for your device.

When developing the latest release of this project, I normally kicked that command off before adding a new Dynamic DNS configuration. Typically I would see a response on the worker within ~2 minutes; but if not, it normally indicated I supplied the configuration values in the UniFi console incorrectly.

**Comment by nathanu** [comment]
Thank you for the response, I actually got it working yesterday. Combination of two things; originally neglecting to append `/update?ip=%i&hostname=%h` onto the worker route string when entering the details into my UCG, and then getting an error when trying to update. Eventually found the note on not being able to update entries due to the bug in UCG OS. Thanks again!

**Comment by willswire** [comment]
No problem! So glad you got it working. Thanks for posting the fix here for others to reference.
