### ISSUE TITLE
Update README.md Instructions

### ISSUE THREAD

**Issue by jordantrizz** [willswire/unifi-ddns#92]
I spent a half hour trying to figure out what the right combination of settings would send the correct information to the Cloudflare Worker. This is what worked for me.

* Server: dyndns
* Hostname: host.domain.com
* Username: domain.com
* Password: cloudflare-token
* Server: home-ddns.workerorg.workers.dev/update?ip=%i&hostname=%h

This works with a UDM Pro on 4.0.21

When using custom, the following occurs.

1. You can't use https:// in the server section
2. Anything in the server after the hostname is added to the config as the name of the service and fails to start.
3. Once you set server to "home-ddns.workerorg.workers.dev" it just sends the following requests
```
GET https://home-ddns.workersorg.workers.dev/updatehost.domain.com
```

I think you could probably update the README.md to include the above information and save some people time.

**Comment by willswire** [comment]
Thanks for taking the time to share what worked for you. I'm preparing to refactor this project entirely here soon in #94. I will include updated documentation for configuring DDNS for the `custom` provider and use that as default.
